# Generated by Django 5.1.6 on 2025-04-03 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='chatmessage',
            table='chat_messages',
        ),
    ]
